FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy app code
COPY . .

# Build the app
RUN npm run build

# Expose port
EXPOSE 3000

# Set environment
ENV NEXT_PUBLIC_API_URL=http://localhost:8000

# Start the app
CMD ["npm", "run", "start"]
